Repository multiversx/mx-sdk-dapp-ui, pull requests merged in 2025-08, with the labels that each got.

#181 Updated styles on transaction table
  CHANGELOG.md
  src/assets/icons/arrow-right-icon/arrow-right-icon.scss
  src/components/controlled/transactions-table/components/transaction-account/transaction-account.tsx
  src/components/controlled/transactions-table/components/transaction-hash/tests/transaction-hash.spec.tsx
  src/components/controlled/transactions-table/components/transaction-hash/transaction-hash.scss
  src/components/controlled/transactions-table/components/transaction-hash/transaction-hash.tsx
  src/components/controlled/transactions-table/components/transaction-icon/transaction-icon.tsx
  src/components/controlled/transactions-table/components/transaction-method/tests/transaction-method.spec.ts
  src/components/controlled/transactions-table/components/transaction-method/transaction-method.scss
  src/components/controlled/transactions-table/components/transaction-method/transaction-method.tsx
  src/components/controlled/transactions-table/components/transaction-shards/tests/transaction-shards.spec.tsx
  src/components/controlled/transactions-table/components/transaction-shards/transaction-shards.scss
  src/components/controlled/transactions-table/components/transaction-shards/transaction-shards.tsx
  src/components/controlled/transactions-table/transactions-table.scss
  src/components/controlled/transactions-table/transactions-table.tsx
  src/global/tailwind.css
  src/global/variables.css
Labels: enhancement

#184 Remove debounce from sign transactions button for immediate response
  CHANGELOG.md
  src/components/functional/sign-transactions-panel/components/sign-transactions-footer/sign-transactions-footer.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-overview/sign-transactions-overview.scss
Labels: enhancement

#198 Toast progress update
  CHANGELOG.md
  src/components/functional/toasts-list/components/transaction-toast/components/transaction-toast-progress/transaction-toast-progress.scss
  src/components/functional/toasts-list/components/transaction-toast/components/transaction-toast-progress/transaction-toast-progress.tsx
Labels: enhancement

#199 v0.0.25
  CHANGELOG.md
  package.json
  src/components/functional/toasts-list/components/transaction-toast/components/transaction-toast-progress/transaction-toast-progress.scss
  src/components/functional/toasts-list/components/transaction-toast/components/transaction-toast-progress/transaction-toast-progress.tsx
Labels: enhancement

#202 Copy Button Enhancements
  CHANGELOG.md
  src/assets/icons/check-icon/check-icon.scss
  src/assets/icons/check-icon/check-icon.tsx
  src/assets/icons/copy-icon/copy-icon.tsx
  src/components.d.ts
  src/components/visual/button/button.scss
  src/components/visual/copy-button/copy-button.scss
  src/components/visual/copy-button/copy-button.tsx
  src/components/visual/copy-button/tests/copy-button.spec.ts
  src/components/visual/data-with-explorer-link/data-with-explorer-link.scss
  src/components/visual/data-with-explorer-link/data-with-explorer-link.tsx
  src/components/visual/explorer-link/explorer-link.tsx
  yarn.lock
Labels: enhancement

#203 Updated transactions table styles
  CHANGELOG.md
  src/assets/icons/multiversx-symbol-icon/multiversx-symbol-icon.scss
  src/assets/icons/multiversx-symbol-icon/multiversx-symbol-icon.tsx
  src/components.d.ts
  src/components/controlled/transactions-table/components/transaction-method/tests/transaction-method.spec.ts
  src/components/controlled/transactions-table/components/transaction-method/transaction-method.scss
  src/components/controlled/transactions-table/components/transaction-method/transaction-method.tsx
  src/components/controlled/transactions-table/components/transaction-value/tests/transaction-value.spec.tsx
  src/components/controlled/transactions-table/components/transaction-value/transaction-value.scss
  src/components/controlled/transactions-table/components/transaction-value/transaction-value.tsx
  src/global/variables.css
Labels: enhancement

#204 v0.0.26
  .github/workflows/npm-publish.yml
  .github/workflows/pre-merge-unit-tests.yml
  CHANGELOG.md
  package.json
  src/assets/icons/check-icon/check-icon.scss
  src/assets/icons/check-icon/check-icon.tsx
  src/assets/icons/copy-icon/copy-icon.tsx
  src/assets/icons/multiversx-symbol-icon/multiversx-symbol-icon.scss
  src/assets/icons/multiversx-symbol-icon/multiversx-symbol-icon.tsx
  src/components.d.ts
  src/components/controlled/transactions-table/components/transaction-method/tests/transaction-method.spec.ts
  src/components/controlled/transactions-table/components/transaction-method/transaction-method.scss
  src/components/controlled/transactions-table/components/transaction-method/transaction-method.tsx
  src/components/controlled/transactions-table/components/transaction-value/tests/transaction-value.spec.tsx
  src/components/controlled/transactions-table/components/transaction-value/transaction-value.scss
  src/components/controlled/transactions-table/components/transaction-value/transaction-value.tsx
  src/components/functional/toasts-list/components/transaction-toast/components/transaction-toast-content/transaction-toast-content.tsx
  src/components/visual/button/button.scss
  src/components/visual/copy-button/copy-button.scss
  src/components/visual/copy-button/copy-button.tsx
  src/components/visual/copy-button/tests/copy-button.spec.ts
  src/components/visual/data-with-explorer-link/data-with-explorer-link.scss
  src/components/visual/data-with-explorer-link/data-with-explorer-link.tsx
  src/components/visual/explorer-link/explorer-link.tsx
  src/components/visual/trim/trim.scss
  src/global/variables.css
  yarn.lock
Labels: bug, enhancement

#210 Fixed conflicts
  src/components.d.ts
  src/components/visual/copy-button/tests/copy-button.spec.ts
Labels: bug

#212 Update version
  CHANGELOG.md
  package.json
Labels: enhancement

#213 Updated styles on toast
  CHANGELOG.md
  src/components.d.ts
  src/components/functional/toasts-list/components/transaction-toast/components/transaction-toast-content/transaction-toast-content.scss
  src/global/variables.css
Labels: enhancement
