Repository multiversx/mx-sdk-dapp-ui, pull requests merged in 2025-05, with the labels that each got.

#89 Added providers customization support
  CHANGELOG.md
  src/components.d.ts
  src/components/common/unlock-button/unlock-button.tsx
  src/components/visual/unlock-panel/components/unlock-provider-button/unlock-provider-button.tsx
  src/components/visual/unlock-panel/components/unlock-provider-intro/unlock-provider-intro.tsx
  src/components/visual/unlock-panel/unlock-panel.tsx
  src/types/provider.types.ts
Labels: enhancement

#87 Fixed sign transactions button states
  CHANGELOG.md
  src/components/functional/sign-transactions-panel/components/sign-transaction-component/sign-transaction-component.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.css
  src/components/functional/sign-transactions-panel/sign-transactions-panel.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.types.ts
Labels: bug

#90 Added Ledger Address Table Preloaders
  CHANGELOG.md
  package.json
  src/assets/icons/arrow-up-right-icon/arrow-up-right-icon.scss
  src/assets/icons/arrow-up-right-icon/arrow-up-right-icon.tsx
  src/assets/icons/extension-provider-icon/extension-provider-icon.scss
  src/assets/icons/extension-provider-icon/extension-provider-icon.tsx
  src/assets/icons/ledger-provider-icon/ledger-provider-icon.scss
  src/assets/icons/ledger-provider-icon/ledger-provider-icon.tsx
  src/assets/icons/magnifying-glass-icon/magnifying-glass-icon.scss
  src/assets/icons/magnifying-glass-icon/magnifying-glass-icon.tsx
  src/assets/icons/metamask-provider-icon/metamask-provider-icon.scss
  src/assets/icons/metamask-provider-icon/metamask-provider-icon.tsx
  src/assets/icons/multiversx-logo-icon/multiversx-logo-icon.scss
  src/assets/icons/multiversx-logo-icon/multiversx-logo-icon.tsx
  src/assets/icons/passkey-provider-icon/passkey-provider-icon.scss
  src/assets/icons/passkey-provider-icon/passkey-provider-icon.tsx
  src/assets/icons/spinner-icon/spinner-icon.scss
  src/assets/icons/spinner-icon/spinner-icon.tsx
  src/assets/icons/wallet-provider-icon/wallet-provider-icon.scss
  src/assets/icons/wallet-provider-icon/wallet-provider-icon.tsx
  src/components.d.ts
  src/components/common/unlock-button/unlock-button.scss
  src/components/common/unlock-button/unlock-button.tsx
  src/components/functional/ledger/ledger-addresses/ledger-addresses.config.ts
  src/components/functional/ledger/ledger-addresses/ledger-addresses.scss
  src/components/functional/ledger/ledger-addresses/ledger-addresses.tsx
  src/components/functional/ledger/ledger-confirm/ledger-confirm.scss
  src/components/functional/ledger/ledger-confirm/ledger-confirm.tsx
  src/components/functional/ledger/ledger-intro/ledger-intro.scss
  src/components/functional/ledger/ledger-intro/ledger-intro.tsx
  src/components/functional/wallet-connect/wallet-connect-flow/wallet-connect-flow.scss
  src/components/visual/pagination/components/pagination-ellipsis-form/pagination-ellipsis-form.scss
  src/components/visual/pagination/components/pagination-ellipsis-form/pagination-ellipsis-form.tsx
  src/components/visual/pagination/helpers/getPagination/getPagination.constants.ts
  src/components/visual/pagination/helpers/getPagination/getPagination.ts
  src/components/visual/pagination/pagination.scss
  src/components/visual/pagination/pagination.tsx
  src/components/visual/preloader/preloader.scss
  src/components/visual/preloader/preloader.tsx
  src/components/visual/side-panel/side-panel.scss
  src/components/visual/tooltip/tooltip.scss
  src/components/visual/unlock-panel/components/unlock-provider-button/unlock-provider-button.tsx
  src/components/visual/unlock-panel/components/unlock-provider-intro/unlock-provider-intro.scss
  src/components/visual/unlock-panel/components/unlock-provider-intro/unlock-provider-intro.tsx
  src/components/visual/unlock-panel/helpers/getProviderButtonIcon.tsx
  src/components/visual/unlock-panel/helpers/index.ts
  src/components/visual/unlock-panel/unlock-panel.scss
  src/components/visual/unlock-panel/unlock-panel.tsx
  yarn.lock
Labels: enhancement

#91 Fix ledger double screen
  CHANGELOG.md
  package.json
  src/components.d.ts
  src/components/visual/unlock-panel/unlock-panel.tsx
  src/components/visual/unlock-panel/unlock-panel.types.ts
  yarn.lock
Labels: bug

#92 0.0.0.alpha-14
  CHANGELOG.md
  README.md
  package.json
  src/assets/icons/arrow-up-right-icon/arrow-up-right-icon.scss
  src/assets/icons/arrow-up-right-icon/arrow-up-right-icon.tsx
  src/assets/icons/extension-provider-icon/extension-provider-icon.scss
  src/assets/icons/extension-provider-icon/extension-provider-icon.tsx
  src/assets/icons/ledger-provider-icon/ledger-provider-icon.scss
  src/assets/icons/ledger-provider-icon/ledger-provider-icon.tsx
  src/assets/icons/magnifying-glass-icon/magnifying-glass-icon.scss
  src/assets/icons/magnifying-glass-icon/magnifying-glass-icon.tsx
  src/assets/icons/metamask-provider-icon/metamask-provider-icon.scss
  src/assets/icons/metamask-provider-icon/metamask-provider-icon.tsx
  src/assets/icons/multiversx-logo-icon/multiversx-logo-icon.scss
  src/assets/icons/multiversx-logo-icon/multiversx-logo-icon.tsx
  src/assets/icons/passkey-provider-icon/passkey-provider-icon.scss
  src/assets/icons/passkey-provider-icon/passkey-provider-icon.tsx
  src/assets/icons/spinner-icon/spinner-icon.scss
  src/assets/icons/spinner-icon/spinner-icon.tsx
  src/assets/icons/wallet-provider-icon/wallet-provider-icon.scss
  src/assets/icons/wallet-provider-icon/wallet-provider-icon.tsx
  src/components.d.ts
  src/components/common/unlock-button/unlock-button.scss
  src/components/common/unlock-button/unlock-button.tsx
  src/components/functional/ledger/ledger-addresses/ledger-addresses.config.ts
  src/components/functional/ledger/ledger-addresses/ledger-addresses.scss
  src/components/functional/ledger/ledger-addresses/ledger-addresses.tsx
  src/components/functional/ledger/ledger-confirm/ledger-confirm.scss
  src/components/functional/ledger/ledger-confirm/ledger-confirm.tsx
  src/components/functional/ledger/ledger-intro/ledger-intro.scss
  src/components/functional/ledger/ledger-intro/ledger-intro.tsx
  src/components/functional/sign-transactions-panel/components/sign-transaction-component/sign-transaction-component.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.css
  src/components/functional/sign-transactions-panel/sign-transactions-panel.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.types.ts
  src/components/functional/wallet-connect/wallet-connect-flow/wallet-connect-flow.scss
  src/components/visual/pagination/components/pagination-ellipsis-form/pagination-ellipsis-form.scss
  src/components/visual/pagination/components/pagination-ellipsis-form/pagination-ellipsis-form.tsx
  src/components/visual/pagination/helpers/getPagination/getPagination.constants.ts
  src/components/visual/pagination/helpers/getPagination/getPagination.ts
  src/components/visual/pagination/pagination.scss
  src/components/visual/pagination/pagination.tsx
  src/components/visual/preloader/preloader.scss
  src/components/visual/preloader/preloader.tsx
  src/components/visual/side-panel/side-panel.scss
  src/components/visual/tooltip/tooltip.scss
  src/components/visual/unlock-panel/components/unlock-provider-button/unlock-provider-button.tsx
  src/components/visual/unlock-panel/components/unlock-provider-intro/unlock-provider-intro.scss
  src/components/visual/unlock-panel/components/unlock-provider-intro/unlock-provider-intro.tsx
  src/components/visual/unlock-panel/helpers/getProviderButtonIcon.tsx
  src/components/visual/unlock-panel/helpers/index.ts
  src/components/visual/unlock-panel/unlock-panel.scss
  src/components/visual/unlock-panel/unlock-panel.tsx
  src/components/visual/unlock-panel/unlock-panel.types.ts
  src/types/provider.types.ts
  yarn.lock
Labels: bug, enhancement

#94 0.0.0-alpha.15
  CHANGELOG.md
  package.json
  src/components/functional/sign-transactions-panel/components/sign-transaction-component/sign-transaction-component.tsx
  src/index.ts
  src/utils/formatAddress.ts
  src/utils/utils.spec.ts
  yarn.lock
Labels: enhancement

#95 Add navigate tx
  src/components.d.ts
  src/components/functional/sign-transactions-panel/components/sign-transactions-action-buttons/sign-transactions-action-buttons.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-advanced/sign-transactions-advanced.css
  src/components/functional/sign-transactions-panel/components/sign-transactions-advanced/sign-transactions-advanced.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.types.ts
  src/components/functional/sign-transactions-panel/signTransactionsPanelStore.ts
Labels: enhancement

#93 Sign screens design
  CHANGELOG.md
  src/assets/icons/arrow-right-icon/arrow-right-icon.scss
  src/assets/icons/arrow-right-icon/arrow-right-icon.tsx
  src/assets/icons/check-icon/check-icon.scss
  src/assets/icons/check-icon/check-icon.tsx
  src/assets/icons/pencil-icon/pencil-icon.scss
  src/assets/icons/pencil-icon/pencil-icon.tsx
  src/components.d.ts
  src/components/functional/ledger/ledger-confirm/ledger-confirm.tsx
  src/components/functional/ledger/ledger.types.ts
  src/components/functional/sign-transactions-panel/components/balance-component/balance-component.css
  src/components/functional/sign-transactions-panel/components/balance-component/balance-component.tsx
  src/components/functional/sign-transactions-panel/components/fungible-component/fungible-component.css
  src/components/functional/sign-transactions-panel/components/fungible-component/fungible-component.tsx
  src/components/functional/sign-transactions-panel/components/sign-transaction-component/components/transaction-fee-component/transaction-fee-component.css
  src/components/functional/sign-transactions-panel/components/sign-transaction-component/components/transaction-fee-component/transaction-fee-component.tsx
  src/components/functional/sign-transactions-panel/components/sign-transaction-component/sign-transaction-component.css
  src/components/functional/sign-transactions-panel/components/sign-transaction-component/sign-transaction-component.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-advanced/sign-transactions-advanced.css
  src/components/functional/sign-transactions-panel/components/sign-transactions-advanced/sign-transactions-advanced.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-advanced/sign-transactions-advanced.types.ts
  src/components/functional/sign-transactions-panel/components/sign-transactions-footer/sign-transactions-footer.scss
  src/components/functional/sign-transactions-panel/components/sign-transactions-footer/sign-transactions-footer.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-overview/sign-transactions-overview.css
  src/components/functional/sign-transactions-panel/components/sign-transactions-overview/sign-transactions-overview.tsx
  src/components/functional/sign-transactions-panel/components/token-component/token-component.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.css
  src/components/functional/sign-transactions-panel/sign-transactions-panel.scss
  src/components/functional/sign-transactions-panel/sign-transactions-panel.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.types.ts
  src/components/functional/sign-transactions-panel/signTransactionsPanelStore.ts
  src/components/visual/pagination/pagination.tsx
  src/components/visual/tooltip/tooltip.scss
  yarn.lock
Labels: enhancement

#114 Updated Sign Transactions Layout
  CHANGELOG.md
  src/assets/icons/angle-left-icon/angle-left-icon.scss
  src/assets/icons/angle-left-icon/angle-left-icon.tsx
  src/assets/icons/angle-right-icon/angle-right-icon.scss
  src/assets/icons/angle-right-icon/angle-right-icon.tsx
  src/assets/wallet-connect-app-gallery.png
  src/assets/wallet-connect-app-store.svg
  src/assets/wallet-connect-download.png
  src/assets/wallet-connect-play-store.png
  src/components.d.ts
  src/components/common/generic-modal/generic-modal.css
  src/components/common/generic-modal/generic-modal.tsx
  src/components/common/generic-modal/generic-modal.types.ts
  src/components/common/generic-modal/tests/generic-modal.spec.tsx
  src/components/common/generic-spinner/generic-spinner.css
  src/components/common/generic-spinner/generic-spinner.tsx
  src/components/common/provider-idle-screen/provider-idle-screen.tsx
  src/components/functional/ledger-connect/components/ledger-addresses/ledger-addresses.scss
  src/components/functional/ledger-connect/components/ledger-addresses/ledger-addresses.tsx
  src/components/functional/ledger-connect/components/ledger-confirm/ledger-confirm.scss
  src/components/functional/ledger-connect/components/ledger-confirm/ledger-confirm.tsx
  src/components/functional/ledger-connect/components/ledger-intro/ledger-intro.scss
  src/components/functional/ledger-connect/components/ledger-intro/ledger-intro.tsx
  src/components/functional/ledger-connect/helpers/getLedgerAddressByIndex.ts
  src/components/functional/ledger-connect/ledger-connect.scss
  src/components/functional/ledger-connect/ledger-connect.tsx
  src/components/functional/ledger-connect/ledger-connect.types.ts
  src/components/functional/ledger/helpers/getLedgerAddressByIndex.ts
  src/components/functional/ledger/ledger-confirm/ledger-confirm.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-footer/sign-transactions-footer.scss
  src/components/functional/sign-transactions-panel/components/sign-transactions-footer/sign-transactions-footer.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-header/sign-transactions-header.scss
  src/components/functional/sign-transactions-panel/components/sign-transactions-header/sign-transactions-header.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.scss
  src/components/functional/sign-transactions-panel/sign-transactions-panel.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.types.ts
  src/components/functional/unlock-panel/components/unlock-panel-footer/unlock-panel-footer.tsx
  src/components/functional/unlock-panel/unlock-panel.tsx
  src/components/functional/wallet-connect/components/wallet-connect-download/index.ts
  src/components/functional/wallet-connect/components/wallet-connect-download/wallet-connect-download.scss
  src/components/functional/wallet-connect/components/wallet-connect-download/wallet-connect-download.tsx
  src/components/functional/wallet-connect/components/wallet-connect-scan/index.ts
  src/components/functional/wallet-connect/components/wallet-connect-scan/wallet-connect-scan.scss
  src/components/functional/wallet-connect/components/wallet-connect-scan/wallet-connect-scan.tsx
  src/components/functional/wallet-connect/wallet-connect-flow/wallet-connect-flow.scss
  src/components/functional/wallet-connect/wallet-connect-flow/wallet-connect-flow.tsx
  src/components/functional/wallet-connect/wallet-connect-provider/wallet-connect-provider.scss
  src/components/functional/wallet-connect/wallet-connect.scss
  src/components/functional/wallet-connect/wallet-connect.tsx
  src/components/visual/side-panel/components/side-panel-header/side-panel-header.scss
  src/components/visual/side-panel/components/side-panel-header/side-panel-header.tsx
  yarn.lock
Labels: enhancement

#115 v0.0.5
  CHANGELOG.md
  package.json
  src/assets/icons/angle-left-icon/angle-left-icon.scss
  src/assets/icons/angle-left-icon/angle-left-icon.tsx
  src/assets/icons/angle-right-icon/angle-right-icon.scss
  src/assets/icons/angle-right-icon/angle-right-icon.tsx
  src/assets/wallet-connect-app-gallery.png
  src/assets/wallet-connect-app-store.svg
  src/assets/wallet-connect-download.png
  src/assets/wallet-connect-play-store.png
  src/components.d.ts
  src/components/common/generic-modal/generic-modal.css
  src/components/common/generic-modal/generic-modal.tsx
  src/components/common/generic-modal/generic-modal.types.ts
  src/components/common/generic-modal/tests/generic-modal.spec.tsx
  src/components/common/generic-spinner/generic-spinner.css
  src/components/common/generic-spinner/generic-spinner.tsx
  src/components/common/provider-idle-screen/provider-idle-screen.tsx
  src/components/functional/ledger-connect/components/ledger-addresses/ledger-addresses.scss
  src/components/functional/ledger-connect/components/ledger-addresses/ledger-addresses.tsx
  src/components/functional/ledger-connect/components/ledger-confirm/ledger-confirm.scss
  src/components/functional/ledger-connect/components/ledger-confirm/ledger-confirm.tsx
  src/components/functional/ledger-connect/components/ledger-intro/ledger-intro.scss
  src/components/functional/ledger-connect/components/ledger-intro/ledger-intro.tsx
  src/components/functional/ledger-connect/helpers/getLedgerAddressByIndex.ts
  src/components/functional/ledger-connect/ledger-connect.scss
  src/components/functional/ledger-connect/ledger-connect.tsx
  src/components/functional/ledger-connect/ledger-connect.types.ts
  src/components/functional/ledger/helpers/getLedgerAddressByIndex.ts
  src/components/functional/ledger/ledger-confirm/ledger-confirm.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-footer/sign-transactions-footer.scss
  src/components/functional/sign-transactions-panel/components/sign-transactions-footer/sign-transactions-footer.tsx
  src/components/functional/sign-transactions-panel/components/sign-transactions-header/sign-transactions-header.scss
  src/components/functional/sign-transactions-panel/components/sign-transactions-header/sign-transactions-header.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.scss
  src/components/functional/sign-transactions-panel/sign-transactions-panel.tsx
  src/components/functional/sign-transactions-panel/sign-transactions-panel.types.ts
  src/components/functional/unlock-panel/components/unlock-panel-footer/unlock-panel-footer.tsx
  src/components/functional/unlock-panel/unlock-panel.tsx
  src/components/functional/wallet-connect/components/wallet-connect-download/index.ts
  src/components/functional/wallet-connect/components/wallet-connect-download/wallet-connect-download.scss
  src/components/functional/wallet-connect/components/wallet-connect-download/wallet-connect-download.tsx
  src/components/functional/wallet-connect/components/wallet-connect-scan/index.ts
  src/components/functional/wallet-connect/components/wallet-connect-scan/wallet-connect-scan.scss
  src/components/functional/wallet-connect/components/wallet-connect-scan/wallet-connect-scan.tsx
  src/components/functional/wallet-connect/wallet-connect-flow/wallet-connect-flow.scss
  src/components/functional/wallet-connect/wallet-connect-flow/wallet-connect-flow.tsx
  src/components/functional/wallet-connect/wallet-connect-provider/wallet-connect-provider.scss
  src/components/functional/wallet-connect/wallet-connect.scss
  src/components/functional/wallet-connect/wallet-connect.tsx
  src/components/visual/side-panel/components/side-panel-header/side-panel-header.scss
  src/components/visual/side-panel/components/side-panel-header/side-panel-header.tsx
  stencil.config.ts
  yarn.lock
Labels: enhancement
